[project]
name = 'gingo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.contract_distribution]
path = 'contracts/contract_distribution.clar'
clarity_version = 1
epoch = 2.05

[contracts.data_availability]
path = 'contracts/data_availability.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_shearing_and_management]
path = 'contracts/data_shearing_and_management.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_storage]
path = 'contracts/data_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.gas_efficient_wallet]
path = 'contracts/gas_efficient_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.res]
path = 'contracts/res.clar'
clarity_version = 2
epoch = 2.5

[contracts.reserve_with_event_history_retrieval]
path = 'contracts/reserve_with_event_history_retrieval.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identity]
path = 'contracts/user_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.weighted_votes]
path = 'contracts/weighted_votes.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
