[project]
name = 'gingo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.contract_distribution]
path = 'contracts/contract_distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_shearing_and_management]
path = 'contracts/data_shearing_and_management.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_storage]
path = 'contracts/data_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.res]
path = 'contracts/res.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identity]
path = 'contracts/user_identity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
